name: ibanking
description: ibanking

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=3.24.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  get_storage: ^2.1.1
  intl: ^0.19.0
  flutter_svg: ^2.0.16
  r_dotted_line_border: ^0.1.1
  carousel_slider: ^5.0.0

  cached_network_image:
#  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics:
  change_app_package_name:
  flutter_launcher_icons:
  rename_app:

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo/appLauncher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logo/
